/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "../sources/calcul.h"
long int convert(long int n) {
  long int bin = 0;
  long int rem, i = 1;

  while (n!=0) {
    rem = n % 2;
    n /= 2;
    bin += rem * i;
    i *= 10;
  }

  return bin;
}
void *
calnull_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return (void *) &result;
}

long *
puiss_1_svc(Param *argp, struct svc_req *rqstp)
{
	static long  result;

	long int i; /* Variable used in loop counter */
    long int number = 1;

    for (i = 0; i < argp->b; ++i)
        number *= argp->a;
	result=number;
	printf("Calculating Power 1\n");
	return &result;
}

long *
dec2bin_1_svc(long int *argp, struct svc_req *rqstp)
{
	static long  result;

	result=convert(*argp);
	printf("Converting %ld to %ld\n",*argp,result);

	return &result;
}

long *
puiss_2_svc(Param *argp, struct svc_req *rqstp)
{
	static long  result;

	long int i; /* Variable used in loop counter */
    long int number = 1;

    for (i = 0; i < argp->b; ++i)
        number *= argp->a;
	result=number;
	printf("Calculating %ld power %ld\n",argp->a,argp->b);
	return &result;
}

long *
dec2bin_2_svc(long int *argp, struct svc_req *rqstp)
{
	static long  result;
	result=convert(*argp);
	printf("Converting %ld to binary %ld\n",*argp,result);

	return &result;
}

long *
dec2hex_2_svc(long int *argp, struct svc_req *rqstp)
{
	static long  result;
	result=*argp;

	return &result;
}
