fact: Factorielle.cpp
	g++ -fopenmp Factorielle.cpp -o program && ./program && rm -f program
sum: Sum.cpp
	g++ -fopenmp Sum.cpp -o program && ./program && rm -f program
sect: TP3.cpp
	g++ -fopenmp TP3.cpp -o program && ./program && rm -f program
clean:
	rm -f program